// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		int i = 0;
		int graetThen = 0;
		int lessThen = 0;
		while (i < N){
			double random = Math.random();
			if (random <= 0.5){
			lessThen++;
			} else {
			graetThen ++;
			}
			i++;
		}
		System.out.println("> 0.5: " + graetThen + " times");
		System.out.println("<= 0.5: " + lessThen + " times");
		if(lessThen != 0){
			double ratio =  (double)graetThen / lessThen;
		System.out.println("Ratio: " + ratio);
		}
	}
}
